### ISSUE TITLE
Single to double digit remaps wrong frames

### ISSUE THREAD

**Issue by GreenBlueClouds** [digits58/xsImport#2]
This might be an issue with after effects in general.

Image sequences that go from a single digit to double digit name has an issue where it only imports an image sequence with the same number of characters.

example: A9, A10 This will only import up to A9

Solution: A09, A10 will solve this problem

**Comment by digits58** [comment]
Confirmed the issue. This is due to the following option "checked" by default when the script is importing sequences:
- [x] Force alphabetical order

This might be considered a useful option although so adding it as a user option unchecked for the user would solve the issue. Easy fix.

**Comment by digits58** [comment]
Attempted fix with 3e19119

**Comment by digits58** [comment]
Considered working
