### ISSUE TITLE
Mid sequence exposure mark outs not accounted for by script.

### ISSUE THREAD

**Issue by GreenBlueClouds** [digits58/xsImport#3]
Script currently does not handle mid sequence frame breaks.

Example: 1-----2-----3--4---5-----X---------6--7---8

Once an exposure is marked out by an X After effects still displays the cel

Solution:

Link mark outs to opacity:
Once a cel is marked out, Opacity is set to 0% then mark the opacity to 100 with a new exposure

**Comment by digits58** [comment]
Attempted to address with e49c001

**Comment by digits58** [comment]
Considered working
