### ISSUE TITLE
Import does not work when an image sequence does not start with 1

### ISSUE THREAD

**Issue by GreenBlueClouds** [digits58/xsImport#4]
Importing does not work when an image sequence does not start with a frame 1

**Comment by digits58** [comment]
Confirmed. Possible to fix but there is a caveat to the behaviour.

![image](https://github.com/digits58/xsImport/assets/115112505/fd0320b2-023c-4814-9be7-5380bd522a71)

The Time Remap numbers corresponding to the exported frame will not match one another, i.e., given A5, A6, and A7. The Time Remap number for A5 will be 1, not 5 (or 4, forgot whether it's off by one), A6 will have 2, and A7 will get 3.

There cannot exist a Time Remap number beyond the number of images imported as a sequence. This could've been sidestepped if the missing frames in the sequence were allowed in the beginning, however this is not supported by AE. Missing frames are allowed in the middle, but not at the beginning:
![image](https://github.com/digits58/xsImport/assets/115112505/a9422f82-73f2-4756-80f1-42f544b21b3f)

**Comment by digits58** [comment]
Attempted fix with [ecd01b7](https://github.com/digits58/xsImport/commit/ecd01b7b32f5fe08159ab151144a26b8d28cf5ad)

**Comment by digits58** [comment]
Reported as fixed
