### ISSUE TITLE
Allow renaming of sheet

### ISSUE THREAD

**Issue by GreenBlueClouds** [digits58/xsImport#5]
Received XDTS files often do not have proper sheet names

Can we have an option to choose default sheet name or rename on import in the script panel?

**Comment by digits58** [comment]
> Renaming of sheet is in regards to how the precomp  and folder is imported into AE
> 
> By default the script names the precomp and folder containing image sequence what ever the sheet name was for the xdts file. It's almost always never named or checked so having an option to decide the name of the precomp/folder would really help with organization
>
> -- GreenBlueClouds

**Comment by digits58** [comment]
![image](https://github.com/digits58/xsImport/assets/115112505/69980238-15fa-4621-9e50-3c186fa00e4c)


![image](https://github.com/digits58/xsImport/assets/115112505/281ed528-50da-4a5a-89b8-78e8777c69c4)

**Comment by digits58** [comment]
Implemented in 80172a8

Checkbox will enable a textbox in which the import can be renamed as
